source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
#gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem 'hyper-spec',       path: '../hyper-spec'
gem 'hyperstack-config', path: '../hyperstack-config'
gem 'hyper-state',      path: '../hyper-state'
gem 'hyper-store',      path: '../hyper-store'
gem 'hyper-component',  path: '../hyper-component'
gem 'hyper-operation',  path: '../hyper-operation'
gem 'hyper-model',      path: '../hyper-model'
# Specify your gem's dependencies in hyper-i18n.gemspec
gemspec
