source 'https://rubygems.org'
gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem 'hyper-component', path: '../hyper-component'
gem 'hyperloop-config', path: '../hyperloop-config'
gemspec
