require "bundler/gem_tasks"
require "rspec/core/rake_task"
require 'webdrivers'
load 'webdrivers/Rakefile'

RSpec::Core::RakeTask.new(:spec)

namespace :spec do
  task :prepare do
  end
end

task :default => :spec
