gem 'rails-hyperstack',  path: '../..'
gem 'hyperstack-config', path: '../../../hyperstack-config'
gem 'hyper-state',       path: '../../../hyper-state'
gem 'hyper-component',   path: '../../../hyper-component'
gem 'hyper-operation',   path: '../../../hyper-operation'
gem 'hyper-model',       path: '../../../hyper-model'
gem 'hyper-router',      path: '../../../hyper-router'
gem 'hyper-spec',        path: '../../../hyper-spec'

gem 'pry'
