#!/bin/bash
#docker run -it -v .:/root/hyperstack ${PRIVATE_REGISTRY}/base20:hyperstack /bin/bash

docker build -t ${PRIVATE_REGISTRY}/base20:hyperstack .
docker push ${PRIVATE_REGISTRY}/base20:hyperstack