version: '3.5'

volumes:
  local_gems:
    external: true
    name: local_gems
#  rails_cache:
#  node_modules:
#  packs:
#  packs-test:

networks:
  default:
    name: development_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CONTAINER_SUBNET}


services:
  #############################
  # Setup the base containers #
  #############################

  hyperstack:
    image: ${PRIVATE_REGISTRY}/base20:hyperstack
    domainname: ${BASE_TEST_DOMAIN}
    hostname: hyperstack
    container_name: "hyperstack"
    entrypoint: ./runone
    stdin_open: true
    tty: true
    working_dir: /root/hyperstack
    environment:
      BUNDLE_PATH: "/root/local_gems"
      DRIVER: "travis" #"${DRIVER}"
      COMPONENT: "${COMPONENT}"
      RUBY_VERSION: "3.2.2" #"${RUBY_VERSION}"
#      RUBY_VERSION: "3.1.4" #"${RUBY_VERSION}"
#      RUBY_VERSION: "2.7.8" #"${RUBY_VERSION}"
#      RUBY_VERSION: "3.0.6" #"${RUBY_VERSION}"
      OPAL_VERSION: "1.7.3" #"${OPAL_VERSION}"
#      OPAL_VERSION: "1.6.1" #"${OPAL_VERSION}"
#      OPAL_VERSION: "1.5.1" #"${OPAL_VERSION}"
      TASK: "${TASK}"
      DB: "${DB}"
    volumes:
      - ${MOUNT_PATH:-..}/hyperstack:/root/hyperstack
      - local_gems:/root/local_gems
    networks:
      default:
