format_version: 10
environments:
  test:
    pipelines:
      - hyperstack
      - hyperstack-build
pipelines:
  hyperstack-build:
    group: hyperstack
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      hyperstack:
        git: https://github.com/mpantel/hyperstack.git
        shallow_clone: false
        auto_update: false
        branch: edge
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            cleanup:
              timeout: 0
              tasks:
                - exec:
                    command: ./create-docker-image
                    run_if: passed
  hyperstack:
    group: hyperstack
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      hyperstack:
        git: https://github.com/mpantel/hyperstack.git
        shallow_clone: false
        auto_update: true
        branch: edge
    stages:
      - cleanup:
          fetch_materials: false
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            cleanup:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - compose
                      - run
                      - --rm
                      - --entrypoint
                      - "/bin/bash -c 'chown -R 1000:1001 /root/hyperstack'"
                      - hyperstack
                    command: docker
                    run_if: passed
      - execute:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            run:
              timeout: 0
              tasks:
              - exec:
                  arguments:
                    - compose
                    - run
                    - --rm
                    - hyperstack
                  command: docker
                  run_if: passed