format_version: 10
environments:
  test:
    pipelines:
      - hyperstack
pipelines:
  hyperstack:
    group: hyperstack
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      hyperstack:
        git: https://github.com/mpantel/hyperstack.git
        shallow_clone: false
        auto_update: true
        branch: edge
    stages:
    - prepare:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          setup:
            timeout: 0
            tasks:
            - exec:
#                arguments:
#                - ''
                command: ./runall
                run_if: passed
