#!/bin/bash

cd /root/hyperstack/ruby/$COMPONENT

bundle install
yarn install

#bundle exec chromedriver-update
mkdir -p /usr/lib/chromium-browser
bundle exec ruby -e 'require "webdrivers";  Webdrivers::Chromedriver.update; puts Webdrivers::Chromedriver.current_version'
cp  ~/.webdrivers/chromedriver /usr/lib/chromium-browser/chromedriver

bundle exec rake spec:prepare
#bundle exec rake $TASK
bundle exec rspec ./spec/deprecation_notices/render_spec.rb