source 'https://rubygems.org'
source ENV['HYPER_DEV_GEM_SOURCE'] if ENV['HYPER_DEV_GEM_SOURCE']

# git_source(:github) do |repo_name|
#   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
#   "https://github.com/#{repo_name}.git"
# end

gem 'rails'
gem 'sqlite3'

gem "opal", '>= 0.11.0'
gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem "opal-rails", '~> 0.9.4'
gem "opal-activesupport", '~> 0.3.1'
require '../../lib/hyperloop/component/version'
gem 'hyper-react', Hyperloop::Component::VERSION #, path: '../../../hyper-react'
gem 'hyper-spec', Hyperloop::Component::VERSION #, path: '../../../hyper-spec'
gem 'hyper-component', path: '../..'
gem 'mini_racer', '~> 0.1.15', platforms: :ruby

gem 'puma'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-steps'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
