source "http://rubygems.org"
gem "rails"
gem 'sqlite3'
gem 'react-rails' #, "1.3.3"
gem 'opal', '~> 0.9.0'
gem 'hyper-react', path: '../../../reactrb'
gem 'opal-rails'#, git: "https://github.com/hyper-react/opal-rails.git"
gem 'therubyracer'
gem 'jquery-cookie-rails'
gem 'byebug'
gem 'pry-rails'
gem 'pry-rescue'
gem 'opal-rspec-rails', github: 'opal/opal-rspec-rails'
gem 'synchromesh', path: "../../.."
gem 'web-console'
gem 'hyper-trace'
#gem 'opal-rspec-rails', git: 'https://github.com/hyper-react/opal-rspec-rails.git'
