source "http://rubygems.org"
gem "rails"
gem 'sqlite3'
gem 'react-rails'
gem 'opal', '~> 0.9.0'
gem 'opal-rails'
gem 'therubyracer'
gem 'jquery-cookie-rails'
gem 'byebug'
gem 'pry-rails'
gem 'pry-rescue'
gem 'opal-rspec-rails', github: 'opal/opal-rspec-rails'
gem 'hyper-mesh', path: "../.."
gem 'web-console'
gem 'hyper-trace'
