source 'https://rubygems.org'
#gem 'opal', '< 1.0'
gem 'hyper-component',   path: '../hyper-component'
gem 'hyper-store',       path: '../hyper-store'
gem 'hyper-state',       path: '../hyper-state'
gem 'hyperstack-config', path: '../hyperstack-config'
#gem 'unparser', path: '../../../unparser'
gemspec
