source 'https://rubygems.org'
gem 'hyper-component',   path: '../hyper-component'
gem 'hyper-store',       path: '../hyper-store'
gem 'hyper-state',       path: '../hyper-state'
gem 'hyperstack-config', path: '../hyperstack-config'
#gem 'unparser', path: '../../../unparser'
gem 'opal', '1.0.5'
gemspec
