source 'https://rubygems.org'
source ENV['HYPER_DEV_GEM_SOURCE'] if ENV['HYPER_DEV_GEM_SOURCE']

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails'
gem 'sqlite3'
gem 'puma'

require '../../lib/hyper-store/version'
gem 'hyper-react', HyperStore::VERSION # path: '../../../hyper-react' #
gem 'hyper-spec', HyperStore::VERSION #, path: '../../../hyper-spec'
gem 'hyper-store', path: '../..'
# gem 'hyperloop-config', path: '../../../hyperloop-config'
gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem "opal-rails", '~> 0.9.4'
gem 'opal-browser'
gem 'mini_racer', platforms: :ruby
gem 'react-rails', '>= 2.4.0', '< 2.5.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-steps'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'rubocop', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
