source 'https://rubygems.org'
gem 'hyperstack-config', path: '../hyperstack-config'
gem 'hyper-state',       path: '../hyper-state'
gem 'hyper-component',   path: '../hyper-component'
gem 'hyper-operation',   path: '../hyper-operation'
gem 'hyper-model',       path: '../hyper-model'
gem 'hyper-router',      path: '../hyper-router'
gem 'hyper-spec',        path: '../hyper-spec'
gem 'webpacker'  # TODO: figure out why these two are necessary!
gem 'turbolinks'
gem "selenium-webdriver", '3.142.7'
gemspec
