require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = "spec/hyper-operation/transports_spec.rb"
end

namespace :spec do
  task :prepare do
    sh %(cd spec/test_app; bundle exec rails db:setup)
  end
end

task :default => :spec
