source 'https://rubygems.org'
gem 'hyper-state',      path: '../hyper-state'
gem 'hyper-component',  path: '../hyper-component'
gem 'hyper-operation',  path: '../hyper-operation'
gem 'hyper-spec', path: '../hyper-spec'
gem 'hyper-trace', path: '../hyper-trace'
gem 'hyperstack-config', path: '../hyperstack-config'
unless ENV['OPAL_VERSION']&.match("0.11")
  gem 'opal-browser', git: 'https://github.com/opal/opal-browser'
end
gemspec
